EDA Exploratory Data Analysis

--Database Exploration

Exploring the structure of the database to have the basic understand of the tables of the database.

--Dimension Exploration

Exploring the dimension in the tables, by SELECT DISTINCT column_name from Table;

--Date Exploration

To understand the timeframe, timeline for which the data is present, by doing MIN order_date or MAX order_date.

Find the difference in the First order and the last order?

SELECT MAX(Order_date) as first_order_date, MIN(Order_date) as last_order_date, TIMESTAMPDIFF (YEAR, MIN(Order_date), MAX(Order_date)) AS order_range_year 
FROM Table;

Actual query: 
SELECT MIN(Order_date) as first_order_date, 
MAX(Order_date) as last_order_date, 
TIMESTAMPDIFF (Year, MIN(Order_date), MAX(Order_date)) AS order_range_year
FROM gold.fact_sales;

Find Oldest and the youngest customer--?

SELECT MIN(birthdate) as oldest_cus, MAX(birthdate) as youngest_cus,
TIMESTAMPDIFF(Year, MAX(birthdate), current_date) as age_Youngest_cus, 
TIMESTAMPDIFF(Year, MIN(birthdate), current_date) as age_oldest_cus
FROM gold.dim_customers;

--Measure Exploration

It is to calculate the highest level of aggregation/lowest level of details.
Such as doing sum, average, count etc…


--Find the total sales?
	
SELECT SUM(sales_amount) FROM gold.fact_sales as Total_sales;
	
--Find total items solds?
	
SELECT SUM(quantity) FROM gold.fact_sales as total_items_sold; 
	
Find the average selling price of the items?
	
SELECT ROUND(AVG(price),2) FROM gold.fact_sales as avg_price;

Find the total number of orders?
	
SELECT COUNT(DISTINCT order_number) as total_orders 
FROM gold.fact_sales;
	
--Find the total number of products.fact_sales
	
SELECT COUNT(product_id) as total_products
FROM gold.dim_products;
	
--Find total number of customers?
	
SELECT COUNT(customer_id) as total_customers 
FROM gold.dim_customers;
	
--Find the total number of customers that placed an order? 
	
SELECT COUNT(DISTINCT customer_key) as total_cust_ordered
FROM gold.fact_sales;
	
SELECT COUNT(*)
FROM (SELECT customer_key
FROM gold.fact_sales
GROUP BY customer_key) as tot;
	
--Form a table with all this info together.
	
SELECT 'Total_sales', SUM(sales_amount) as Measure_Value 
FROM gold.fact_sales
UNION ALL
SELECT 'Total_quantity', SUM(quantity)  as Measure_Value 
FROM gold.fact_sales
UNION ALL
SELECT 'Average_price', ROUND(AVG(price),2) 
FROM gold.fact_sales
UNION ALL
SELECT 'Total_orders', COUNT(DISTINCT order_number)
FROM gold.fact_sales
UNION ALL
SELECT 'Total_products', COUNT(product_id)
FROM gold.dim_products
UNION ALL
SELECT 'Total_customers', COUNT(customer_id) 
FROM gold.dim_customers
UNION ALL
SELECT 'Total_customer_orders', COUNT(DISTINCT customer_key)
FROM gold.fact_sales;

--Magnitude analysis: It is like measure by dimensions, e.g. Count by Country, we do aggregate and then group by country.

Find the number of customers by country?

SELECT country, COUNT(customer_key) tot_cus FROM gold.dim_customers
GROUP BY country
ORDER BY tot_cus DESC;

Find total customers by a gender?

SELECT gender, COUNT(customer_key) tot_cus FROM gold.dim_customers
GROUP BY gender;

Find total products by catagory.

SELECT catagory, COUNT(product_id) as tot_prd FROM gold.dim_products
GROUP BY catagory;

Find avg costs in each catagory?

SELECT catagory, AVG(cost) as tot_avg FROM gold.dim_products
GROUP BY catagory;

Find total revenue generated for each catagory?

SELECT catagory, SUM(sales_amount) as tot_sal FROM gold.fact_sales fs
JOIN gold.dim_products dp ON fs.product_key = dp.product_key
GROUP BY catagory;

Find total revenue generated by each customer?

SELECT DISTINCT customer_key as ck, SUM(sales_amount) as tot_s 
FROM gold.fact_sales
GROUP BY ck;

Find total items sold by each country?

SELECT country, SUM(quantity) as total_items_sold FROM
gold.fact_sales fs
JOIN gold.dim_customers dc ON fs.customer_key = dc.customer_key
GROUP BY country;

--Ranking Analysis: Ranking Dimensions by measures, such as ranking country by total_sales.

Find 5 products which generate highest revenue?

SELECT DISTINCT product_name, sum(sales_amount) FROM gold.fact_sales fs
JOIN gold.dim_products dp on fs.product_key = dp.product_key
group by product_name
order by sum(sales_amount) DESC
LIMIT 5;

Find 5 products which generate Lowest revenue?

SELECT DISTINCT product_name, sum(sales_amount) FROM gold.fact_sales fs
JOIN gold.dim_products dp on fs.product_key = dp.product_key
group by product_name
order by sum(sales_amount)
LIMIT 5;

Another way

SELECT * FROM (
SELECT 
product_name, sum(sales_amount), 
ROW_NUMBER() 
OVER (order by sum(sales_amount) desc) rn
FROM gold.fact_sales fs
JOIN gold.dim_products dp on fs.product_key = dp.product_key
group by product_name)t
WHERE rn <=5;
 
Find the top 10 customers who have generated the highest revenue?

SELECT * FROM (
SELECT customer_id, 
first_name, 
last_name,
sum(sales_amount), 
ROW_NUMBER() 
OVER (order by sum(sales_amount) desc) rn
FROM gold.fact_sales fs
JOIN gold.dim_customers dc on fs.customer_key = dc.customer_key
group by customer_id, 
first_name, 
last_name)t
WHERE rn <=10;

Find the customers with fewer orders only?

SELECT * FROM (
SELECT fs.customer_key, customer_id, 
first_name, 
last_name,
COUNT(order_number), 
ROW_NUMBER() 
OVER (order by COUNT(order_number)) rn
FROM gold.fact_sales fs
JOIN gold.dim_customers dc on fs.customer_key = dc.customer_key
group by customer_id, 
first_name, 
last_name)t
WHERE rn <=5;
